POST http://localhost:2020/Login/VerifyUser 
Content-Type: application/json

{
    "login":"123haha",
    "pass":"8c10bf82e762a"
}
####
POST http://localhost:2020/Subscription
Content-Type: application/json

{
    "name":"Yassuo",
    "lastname":"KingValtr",
    "Password":"123456",
    "Username":"Sneeko",
    "Email":"123@gmail.com",
    "cin":"12345678"
}
####
POST http://localhost:2020/API1
Content-Type: application/json

{
    "cin":26307178
}
###
POST http://localhost:2020/API2
Content-Type: application/json

{
    "name":"Dani",
    "lastname":"O'Currigan",
    "fathername":"Bryce",
    "mothername":"Kaitlin"
}
###
POST http://localhost:2020/MDBReset
Content-Type: application/json

{
     "SecretCode":"123",
     "NP":"Yassuo123",
     "UUID":"2d977378-dd88-44ce-99bc-ecc2e1a88049"
}
###

POST http://localhost:2020/EMAIL
Content-Type: application/json

{
  "UUID":"14a8ab09-3a76-49c2-8227-47ec7b946839"
}
###
POST http://127.0.0.1:2020/SMS
Content-Type: application/json

{
    "Phone":"+21622495131"
}

###
POST http://127.0.0.1:2020/Applications/Insert
Content-Type: application/json

{
    "CIN":87957819,
    "Name":"Madline",
    "Last Name":"Midford",
    "Demande":"TMP",
    "Description":"MeowMoesMoew saha",
    "Status":"Accepted",
    "Date":"17-11-2002",
    "Starting Date":"17-11-2002",
    "Ending Date ":"17-11-2002"

}
###
POST http://127.0.0.1:2020/Applications/GetUserRequests
Content-Type: application/json

{
    "cin":87957819
}
###
POST http://127.0.0.1:2020/AfterLogin/getCredentialsFromLogin
Content-Type: application/json

{
    "name":"Madeleine",
    "ln":"Midford"
}
###
GET http://127.0.0.1:3000/json